from typing import NamedTuple


class Software(NamedTuple):
    id: str
    name: str
    description: str
    url: str
    icon: str  # Bootstrap Icons class name
    category: str
    platforms: tuple[str, ...]
    license: str  # 'open' or 'proprietary'


# Categories for display ordering and grouping
SOFTWARE_CATEGORIES: tuple[tuple[str, str], ...] = (
    ('editor', 'Editors'),
    ('mobile', 'Mobile Apps'),
    ('navigation', 'Navigation & Routing'),
    ('viewer', 'Map Viewers'),
    ('tool', 'Tools & Libraries'),
    ('service', 'Services'),
)

SOFTWARE_CATEGORY_MAP: dict[str, str] = dict(SOFTWARE_CATEGORIES)

SOFTWARE_PLATFORMS: tuple[str, ...] = (
    'web',
    'android',
    'ios',
    'windows',
    'linux',
    'macos',
)

SOFTWARE_LIST: list[Software] = sorted(
    [
        # --- Editors ---
        Software(
            id='id-editor',
            name='iD',
            description='The default web-based editor on openstreetmap.org. Easy to use for beginners with a guided walkthrough.',
            url='https://wiki.openstreetmap.org/wiki/ID',
            icon='bi-pencil-square',
            category='editor',
            platforms=('web',),
            license='open',
        ),
        Software(
            id='josm',
            name='JOSM',
            description='A powerful desktop editor for advanced users. Supports plugins, offline editing, and bulk operations.',
            url='https://josm.openstreetmap.de',
            icon='bi-pencil-square',
            category='editor',
            platforms=('windows', 'linux', 'macos'),
            license='open',
        ),
        Software(
            id='rapid',
            name='Rapid',
            description='A web-based editor by Meta with AI-assisted features for verifying and adding map data.',
            url='https://rapideditor.org',
            icon='bi-lightning-charge',
            category='editor',
            platforms=('web',),
            license='open',
        ),
        Software(
            id='vespucci',
            name='Vespucci',
            description='A full-featured OpenStreetMap editor for Android with support for all OSM data types.',
            url='https://vespucci.io',
            icon='bi-phone',
            category='editor',
            platforms=('android',),
            license='open',
        ),
        Software(
            id='go-map',
            name='Go Map!!',
            description='A feature-rich OSM editor for Apple devices with aerial imagery and GPS track support.',
            url='https://wiki.openstreetmap.org/wiki/Go_Map!!',
            icon='bi-phone',
            category='editor',
            platforms=('ios', 'macos'),
            license='open',
        ),
        Software(
            id='streetcomplete',
            name='StreetComplete',
            description='An Android app for adding map details through simple quests. Great for surveying while walking.',
            url='https://streetcomplete.app',
            icon='bi-check2-circle',
            category='editor',
            platforms=('android',),
            license='open',
        ),
        Software(
            id='every-door',
            name='Every Door',
            description='A mobile editor focused on POI and address data. Quick and easy for adding shops, amenities, and buildings.',
            url='https://every-door.app',
            icon='bi-door-open',
            category='editor',
            platforms=('android', 'ios'),
            license='open',
        ),
        # --- Mobile Apps ---
        Software(
            id='osmand',
            name='OsmAnd',
            description='An offline maps and navigation app with worldwide coverage, turn-by-turn routing, and POI search.',
            url='https://osmand.net',
            icon='bi-compass',
            category='mobile',
            platforms=('android', 'ios'),
            license='open',
        ),
        Software(
            id='organic-maps',
            name='Organic Maps',
            description='A fast, privacy-focused offline maps app for hiking, cycling, and driving. No ads or trackers.',
            url='https://organicmaps.app',
            icon='bi-tree',
            category='mobile',
            platforms=('android', 'ios'),
            license='open',
        ),
        Software(
            id='magic-earth',
            name='Magic Earth',
            description='A free navigation app with turn-by-turn directions, traffic info, and crowd-sourced speed cameras.',
            url='https://www.magicearth.com',
            icon='bi-globe2',
            category='mobile',
            platforms=('android', 'ios'),
            license='proprietary',
        ),
        # --- Navigation & Routing ---
        Software(
            id='osrm',
            name='OSRM',
            description='The Open Source Routing Machine. A high-performance routing engine for shortest paths in road networks.',
            url='https://project-osrm.org',
            icon='bi-signpost-split',
            category='navigation',
            platforms=('web', 'linux'),
            license='open',
        ),
        Software(
            id='graphhopper',
            name='GraphHopper',
            description='A fast and flexible routing engine supporting car, bike, and pedestrian profiles with isochrone analysis.',
            url='https://www.graphhopper.com',
            icon='bi-signpost-split',
            category='navigation',
            platforms=('web', 'linux', 'windows', 'macos'),
            license='open',
        ),
        Software(
            id='valhalla',
            name='Valhalla',
            description='An open-source routing engine with time-distance matrix, isochrone, and map-matching capabilities.',
            url='https://github.com/valhalla/valhalla',
            icon='bi-signpost-split',
            category='navigation',
            platforms=('web', 'linux'),
            license='open',
        ),
        Software(
            id='navit',
            name='Navit',
            description='An open-source car navigation system with real-time GPS tracking and voice guidance.',
            url='https://www.navit-project.org',
            icon='bi-car-front',
            category='navigation',
            platforms=('windows', 'linux', 'macos', 'android'),
            license='open',
        ),
        # --- Map Viewers ---
        Software(
            id='qgis',
            name='QGIS',
            description='A professional GIS application for viewing, editing, and analyzing geospatial data with OSM layers.',
            url='https://qgis.org',
            icon='bi-layers',
            category='viewer',
            platforms=('windows', 'linux', 'macos'),
            license='open',
        ),
        Software(
            id='marble',
            name='Marble',
            description='A virtual globe and world atlas with OSM data, supporting multiple projections and offline maps.',
            url='https://marble.kde.org',
            icon='bi-globe-americas',
            category='viewer',
            platforms=('windows', 'linux', 'macos'),
            license='open',
        ),
        Software(
            id='gpxsee',
            name='GPXSee',
            description='A GPS log viewer and analyzer supporting GPX, TCX, KML, and other formats with OSM maps.',
            url='https://www.gpxsee.org',
            icon='bi-graph-up',
            category='viewer',
            platforms=('windows', 'linux', 'macos'),
            license='open',
        ),
        # --- Tools & Libraries ---
        Software(
            id='maplibre',
            name='MapLibre GL',
            description='An open-source library for rendering interactive vector maps in web browsers and mobile apps.',
            url='https://maplibre.org',
            icon='bi-code-slash',
            category='tool',
            platforms=('web', 'android', 'ios'),
            license='open',
        ),
        Software(
            id='leaflet',
            name='Leaflet',
            description='A lightweight JavaScript library for mobile-friendly interactive maps. Powers countless websites.',
            url='https://leafletjs.com',
            icon='bi-code-slash',
            category='tool',
            platforms=('web',),
            license='open',
        ),
        Software(
            id='mapnik',
            name='Mapnik',
            description='A toolkit for rendering beautiful maps from OSM data. Powers the default map tiles on openstreetmap.org.',
            url='https://mapnik.org',
            icon='bi-brush',
            category='tool',
            platforms=('windows', 'linux', 'macos'),
            license='open',
        ),
        Software(
            id='overpass-api',
            name='Overpass API',
            description='A read-only API for querying OSM data with custom filters. Lets you extract exactly the data you need.',
            url='https://overpass-turbo.eu',
            icon='bi-database',
            category='tool',
            platforms=('web',),
            license='open',
        ),
        Software(
            id='osmium',
            name='Osmium',
            description='A fast C++ library and command-line tool for working with OSM data files (PBF, XML).',
            url='https://osmcode.org/osmium-tool/',
            icon='bi-terminal',
            category='tool',
            platforms=('windows', 'linux', 'macos'),
            license='open',
        ),
        # --- Services ---
        Software(
            id='nominatim',
            name='Nominatim',
            description='The geocoding service behind OSM search. Converts addresses to coordinates and vice versa.',
            url='https://nominatim.org',
            icon='bi-search',
            category='service',
            platforms=('web',),
            license='open',
        ),
        Software(
            id='openrouteservice',
            name='openrouteservice',
            description='A routing service providing directions, isochrones, and distance matrices based on OSM data.',
            url='https://openrouteservice.org',
            icon='bi-sign-turn-right',
            category='service',
            platforms=('web',),
            license='open',
        ),
        Software(
            id='switch2osm',
            name='switch2osm',
            description='A guide for organizations wanting to switch from commercial map providers to OpenStreetMap.',
            url='https://switch2osm.org',
            icon='bi-arrow-repeat',
            category='service',
            platforms=('web',),
            license='open',
        ),
    ],
    key=lambda s: s.name.casefold(),
)
