"""Unified user subscription interface

Revision ID: fdac1daabf02
Revises: 4312fe3b1209
Create Date: 2024-11-21 08:49:07.012519+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fdac1daabf02'
down_revision: str | None = '4312fe3b1209'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_subscription',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('target', sa.Enum('changeset', 'diary', 'note', 'user', name='usersubscriptiontarget'), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('target', 'target_id', 'user_id')
    )
    op.drop_table('friendship')
    op.drop_table('diary_subscription')
    op.drop_table('changeset_subscription')
    op.drop_table('note_subscription')
    op.alter_column('diary', 'body',
               existing_type=sa.TEXT(),
               type_=sa.Unicode(length=100000),
               existing_nullable=False)
    op.create_index('diary_language_idx', 'diary', ['language', 'id'], unique=False)
    op.create_index('diary_user_id_idx', 'diary', ['user_id', 'id'], unique=False)
    op.create_index('trace_tags_idx', 'trace', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('trace_visibility_user_id_idx', 'trace', ['visibility', 'user_id', 'id'], unique=False)
    op.drop_column('user_block', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    ...
