"""PATs label->name

Revision ID: 622ef2d5cc8e
Revises: 4f0970c3d89e
Create Date: 2024-10-17 11:20:23.389310+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '622ef2d5cc8e'
down_revision: str | None = '4f0970c3d89e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth2_token', sa.Column('name', sa.Unicode(length=50), nullable=True))
    op.drop_column('oauth2_token', 'label')
    # ### end Alembic commands ###


def downgrade() -> None:
    ...
