"""Remove password_extra user field

Revision ID: 5dbfbd688364
Revises: 88eea8344915
Create Date: 2024-06-17 10:44:10.416638+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5dbfbd688364'
down_revision: str | None = '88eea8344915'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_extra')
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
