"""Nullable trace seg arrays

Revision ID: 5aebf3a93d4a
Revises: 8f58012a1d55
Create Date: 2024-07-01 08:52:27.122334+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5aebf3a93d4a'
down_revision: str | None = '8f58012a1d55'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trace_segment', 'capture_times',
               existing_type=postgresql.ARRAY(postgresql.TIMESTAMP(timezone=True)),
               nullable=True)
    op.alter_column('trace_segment', 'elevations',
               existing_type=postgresql.ARRAY(sa.REAL()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
