"""UserToken stuff

Revision ID: 443c2e65c8cf
Revises: 175e464cf823
Create Date: 2024-12-12 12:50:42.543356+00:00

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '443c2e65c8cf'
down_revision: str | None = '175e464cf823'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_token_account_confirm', 'expires_at')
    op.drop_column('user_token_email_change', 'expires_at')
    op.drop_column('user_token_email_reply', 'expires_at')
    op.drop_column('user_token_reset_password', 'expires_at')
    # ### end Alembic commands ###


def downgrade() -> None: ...
