"""Nullable token_hashed

Revision ID: 7346197d7b38
Revises: 622ef2d5cc8e
Create Date: 2024-10-17 13:42:24.650081+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7346197d7b38'
down_revision: str | None = '622ef2d5cc8e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oauth2_token', 'token_hashed',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.create_index('oauth2_token_authorized_user_app_idx', 'oauth2_token', ['user_id', 'application_id', 'id'], unique=False, postgresql_where=sa.text('authorized_at IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    ...
