"""PATs

Revision ID: 4f0970c3d89e
Revises: 1e23c648010a
Create Date: 2024-10-17 10:35:35.730236+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4f0970c3d89e'
down_revision: str | None = '1e23c648010a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth2_token', sa.Column('label', sa.Unicode(length=50), nullable=True))
    op.add_column('oauth2_token', sa.Column('token_preview', sa.Unicode(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    ...
