"""Add note comment index

Revision ID: 59829d1eb579
Revises: d29aeba5a5f6
Create Date: 2024-11-01 19:36:18.556186+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '59829d1eb579'
down_revision: str | None = 'd29aeba5a5f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('note_comment_note_created_idx', 'note_comment', ['note_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    ...
