"""Remove terms page

Revision ID: e9d9debb2015
Revises: 6f2c11643bc5
Create Date: 2024-11-10 06:21:51.732805+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e9d9debb2015'
down_revision: str | None = '6f2c11643bc5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('connected_account', 'uid',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Unicode(length=255),
               existing_nullable=False)
    op.alter_column('user_pref', 'app_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    ...
