"""Make trace point time optional

Revision ID: h7kn239k5b83
Revises: 5dbfbd688364
Create Date: 2024-06-27 14:33:36.48264+00:00

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'h7kn239k5b83'
down_revision: str | None = '5dbfbd688364'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trace_point', 'captured_at', nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
