"""Deleted users index

Revision ID: 0f064c631071
Revises: 65f76d4886fc
Create Date: 2025-02-03 02:31:13.673829+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0f064c631071'
down_revision: str | None = '65f76d4886fc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'user_deleted_idx',
        'user',
        ['id'],
        unique=False,
        postgresql_where=sa.text("email LIKE '%' || '@deleted.invalid'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'user_deleted_idx', table_name='user', postgresql_where=sa.text("email LIKE '%' || '@deleted.invalid'")
    )
    # ### end Alembic commands ###
