import datetime
from collections.abc import Callable, Iterable, Iterator, KeysView, Mapping, Sequence
from dataclasses import dataclass
from typing import Protocol, TypeVar, overload

from google.protobuf import descriptor as _descriptor
from google.protobuf import duration_pb2 as _duration_pb2
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.message import Message

type JsonValue = (
    None | bool | float | str | Mapping[str, 'JsonValue'] | Sequence['JsonValue']
)


@dataclass(frozen=True)
class FileAugment:
    proto_file: str
    type_aliases: dict[str, object]


@dataclass(frozen=True)
class MessageAugment:
    proto_name: str  # fully-qualified, leading dot
    protocol: type[Protocol]


_FILE_AUGMENTS: dict[str, FileAugment] = {}
_MESSAGE_AUGMENTS: dict[str, MessageAugment] = {}

_T = TypeVar('_T')


def register_file(
    proto_file: str, *, type_aliases: Mapping[str, object] | None = None
) -> Callable[[_T], _T]:
    def deco(obj: _T) -> _T:
        _FILE_AUGMENTS[proto_file] = FileAugment(
            proto_file=proto_file,
            type_aliases=dict(type_aliases or {}),
        )
        return obj

    return deco


def register_message(proto_name: str) -> Callable[[type[Protocol]], type[Protocol]]:
    def deco(cls: type[Protocol]) -> type[Protocol]:
        _MESSAGE_AUGMENTS[proto_name] = MessageAugment(
            proto_name=proto_name, protocol=cls
        )
        return cls

    return deco


def file_augments(proto_file: str) -> FileAugment | None:
    return _FILE_AUGMENTS.get(proto_file)


def message_augment(proto_name: str) -> MessageAugment | None:
    return _MESSAGE_AUGMENTS.get(proto_name)


@register_file('google/protobuf/struct.proto', type_aliases={'JsonValue': JsonValue})
def _register_struct_module_augments() -> None: ...


@register_message('.google.protobuf.Timestamp')
class TimestampAugment(Protocol):
    def ToDatetime(self, tzinfo: datetime.tzinfo | None = ...) -> datetime.datetime: ...
    def FromDatetime(self, dt: datetime.datetime) -> None: ...
    def ToJsonString(self) -> str: ...
    def FromJsonString(self, value: str) -> None: ...
    def GetCurrentTime(self) -> None: ...

    def ToNanoseconds(self) -> int: ...
    def ToMicroseconds(self) -> int: ...
    def ToMilliseconds(self) -> int: ...
    def ToSeconds(self) -> int: ...

    def FromNanoseconds(self, nanos: int) -> None: ...
    def FromMicroseconds(self, micros: int) -> None: ...
    def FromMilliseconds(self, millis: int) -> None: ...
    def FromSeconds(self, seconds: int) -> None: ...

    @overload
    def __add__(self, value: datetime.timedelta) -> datetime.datetime: ...
    @overload
    def __add__(self, value: _duration_pb2.Duration) -> datetime.datetime: ...
    def __add__(self, value): ...

    @overload
    def __radd__(self, value: datetime.timedelta) -> datetime.datetime: ...
    @overload
    def __radd__(self, value: _duration_pb2.Duration) -> datetime.datetime: ...
    def __radd__(self, value): ...

    @overload
    def __sub__(self, value: datetime.timedelta) -> datetime.datetime: ...
    @overload
    def __sub__(self, value: _duration_pb2.Duration) -> datetime.datetime: ...
    @overload
    def __sub__(self, value: datetime.datetime) -> datetime.timedelta: ...
    @overload
    def __sub__(self, value: 'Timestamp') -> datetime.timedelta: ...
    def __sub__(self, value): ...

    def __rsub__(self, dt: datetime.datetime) -> datetime.timedelta: ...


@register_message('.google.protobuf.Duration')
class DurationAugment(Protocol):
    def ToTimedelta(self) -> datetime.timedelta: ...
    def FromTimedelta(self, td: datetime.timedelta) -> None: ...
    def ToJsonString(self) -> str: ...
    def FromJsonString(self, value: str) -> None: ...

    def ToNanoseconds(self) -> int: ...
    def ToMicroseconds(self) -> int: ...
    def ToMilliseconds(self) -> int: ...
    def ToSeconds(self) -> int: ...

    def FromNanoseconds(self, nanos: int) -> None: ...
    def FromMicroseconds(self, micros: int) -> None: ...
    def FromMilliseconds(self, millis: int) -> None: ...
    def FromSeconds(self, seconds: int) -> None: ...

    @overload
    def __add__(self, value: datetime.timedelta) -> datetime.timedelta: ...
    @overload
    def __add__(self, value: 'Duration') -> datetime.timedelta: ...
    @overload
    def __add__(self, value: datetime.datetime) -> datetime.datetime: ...
    @overload
    def __add__(self, value: _timestamp_pb2.Timestamp) -> datetime.datetime: ...
    def __add__(self, value): ...

    __radd__ = __add__

    @overload
    def __sub__(self, value: datetime.timedelta) -> datetime.timedelta: ...
    @overload
    def __sub__(self, value: 'Duration') -> datetime.timedelta: ...
    def __sub__(self, value): ...

    @overload
    def __rsub__(self, value: datetime.datetime) -> datetime.datetime: ...
    @overload
    def __rsub__(self, value: datetime.timedelta) -> datetime.timedelta: ...
    @overload
    def __rsub__(self, value: _timestamp_pb2.Timestamp) -> datetime.datetime: ...
    def __rsub__(self, value): ...


@register_message('.google.protobuf.Any')
class AnyAugment(Protocol):
    def Pack(
        self,
        msg: Message,
        type_url_prefix: str = ...,
        deterministic: bool | None = ...,
    ) -> None: ...
    def Unpack(self, msg: Message) -> bool: ...
    def TypeName(self) -> str: ...
    def Is(self, descriptor: _descriptor.Descriptor) -> bool: ...


@register_message('.google.protobuf.FieldMask')
class FieldMaskAugment(Protocol):
    def ToJsonString(self) -> str: ...
    def FromJsonString(self, value: str) -> None: ...
    def IsValidForDescriptor(self, message_descriptor: _descriptor.Descriptor) -> bool: ...
    def AllFieldsFromDescriptor(self, message_descriptor: _descriptor.Descriptor) -> None: ...
    def CanonicalFormFromMask(self, mask: 'FieldMask') -> None: ...
    def Union(self, mask1: 'FieldMask', mask2: 'FieldMask') -> None: ...
    def Intersect(self, mask1: 'FieldMask', mask2: 'FieldMask') -> None: ...
    def MergeMessage(
        self,
        source: Message,
        destination: Message,
        replace_message_field: bool = ...,
        replace_repeated_field: bool = ...,
    ) -> None: ...


@register_message('.google.protobuf.Struct')
class StructAugment(Protocol):
    def __getitem__(self, key: str) -> 'JsonValue': ...
    def __setitem__(self, key: str, value: 'JsonValue') -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[str]: ...

    def keys(self) -> KeysView[str]: ...
    def values(self) -> list['JsonValue']: ...
    def items(self) -> list[tuple[str, 'JsonValue']]: ...
    def update(self, dictionary: Mapping[str, 'JsonValue']) -> None: ...

    def get_or_create_list(self, key: str) -> 'ListValue': ...
    def get_or_create_struct(self, key: str) -> 'Struct': ...


@register_message('.google.protobuf.ListValue')
class ListValueAugment(Protocol):
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> 'JsonValue': ...
    def __setitem__(self, index: int, value: 'JsonValue') -> None: ...
    def __delitem__(self, key: int) -> None: ...

    def append(self, value: 'JsonValue') -> None: ...
    def extend(self, elem_seq: Iterable['JsonValue']) -> None: ...
    def items(self) -> Iterator['JsonValue']: ...

    def add_struct(self) -> 'Struct': ...
    def add_list(self) -> 'ListValue': ...
