from typing import Any, Literal, overload

class CDATA:
    def __init__(self, text: str, /) -> None: ...

def buffered_randbytes(n: int, /) -> bytes: ...
def buffered_rand_urlsafe(n: int, /) -> str: ...
def buffered_rand_storage_key(suffix: str = '') -> str: ...
def element_type(s: str) -> str: ...
def typed_element_id(type_: str, id: int) -> int: ...
def versioned_typed_element_id(type_: str, s: str) -> tuple[int, int]: ...
def split_typed_element_id(id: int) -> tuple[str, int]: ...
def split_typed_element_ids(
    ids: list[int | dict[str, Any]],
) -> list[tuple[str, int]]: ...
def xattr_json(name: str, /, xml: str | None = None) -> str: ...
def xattr_xml(name: str, /, xml: str | None = None) -> str: ...
def xml_parse(xml: bytes, /) -> dict[str, Any]: ...
@overload
def xml_unparse(root: dict[str, Any], binary: Literal[True], /) -> bytes: ...
@overload
def xml_unparse(root: dict[str, Any], binary: Literal[False] = False, /) -> str: ...
def xml_unparse(root: dict[str, Any], binary: bool = False, /) -> str | bytes: ...
