from typing import Any, Literal, LiteralString, overload

from app.models.db.element import Element, ElementInit
from app.models.element import ElementId, ElementType, TypedElementId
from app.models.types import StorageKey

class CDATA:
    def __init__(self, text: str, /) -> None: ...

def buffered_randbytes(n: int, /) -> bytes: ...
def buffered_rand_urlsafe(n: int, /) -> str: ...
def buffered_rand_storage_key(suffix: LiteralString = '') -> StorageKey: ...
def element_id(typed_id: TypedElementId, /) -> ElementId: ...
def element_type(typed_id: TypedElementId, /) -> ElementType: ...
def typed_element_id(type: ElementType, id: ElementId, /) -> TypedElementId: ...
def versioned_typed_element_id(
    type: ElementType, s: str, /
) -> tuple[TypedElementId, int]: ...
def split_typed_element_id(id: TypedElementId, /) -> tuple[ElementType, ElementId]: ...
def split_typed_element_ids(
    ids: list[TypedElementId] | list[Element] | list[ElementInit], /
) -> list[tuple[ElementType, ElementId]]: ...
def xattr_json(name: str, /, xml=None) -> str: ...
def xattr_xml(name: str, /, xml: LiteralString | None = None) -> str: ...
def xml_parse(xml: bytes, /) -> dict[str, Any]: ...
@overload
def xml_unparse(root: dict[str, Any], binary: Literal[True], /) -> bytes: ...
@overload
def xml_unparse(root: dict[str, Any], binary: Literal[False] = False, /) -> str: ...
def xml_unparse(root: dict[str, Any], binary: bool = False, /) -> str | bytes: ...
