import "./main.scss"

import "@runtime/polyfills"

import "@runtime/tracking"

import "@utils/i18n"

import "./edit/redirect"

import "./navbar/navbar-left"
import "./navbar/navbar-right"

import "@components/datetime-inputs"
import "@runtime/image-proxy"

import "@runtime/timezone-update"
import "@runtime/test-site-watermark"
import "@runtime/unsubscribe-modal"
import "./about"
import "./admin/applications/index"
import "./admin/tasks"
import "./admin/users/edit"
import "./admin/users/index"
import "./audit/index"
import "./communities"
import "./copyright"
import "./diary/compose"
import "./diary/details"
import "./diary/index"
import "./diary/user-comments"
import "./edit/index"
import "./fixthemap"
import "./follows/index"
import "./help"
import "./messages/index"
import "./messages/new"
import "./notes"
import "./oauth2/authorize"
import "./oauth2/fragment-callback"
import "./oauth2/response-form-post"
import "./reports/index"
import "./reports/show"
import "./settings/applications/edit"
import "./settings/applications/index"
import "./settings/connections"
import "./settings/email"
import "./settings/security"
import "./settings/index"
import "./traces/details"
import "./traces/edit"
import "./traces/index"
import "./traces/upload"
import "./user/account-confirm"
import "./user/auth-provider-not-found"
import "./user/login"
import "./user/profile/profile"
import "./user/reset-password"
import "./user/signup"
import "./welcome"

import "./index/app"

import "@components/bootstrap-wrappers"
import "@components/copy-group"
import "@components/report"
import "@utils/password-strength"
